# Admin Service Port
server:
  port: 9003

flyway:
  enabled: true
  locations: classpath:migration
  schemas: [grand]

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/grand
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  typeAliasesPackage: com.spsolutions.grand.domain
  mapperLocations: classpath:mappers/*.xml

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
    fetch-registry: true