CREATE TABLE MASTER_QUESTION_TEMPLATE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_EVENT_TYPE BIGINT(20),
  NAME VARCHAR(255) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_EVENT_TYPE) REFERENCES MASTER_EVENT_TYPE (ID)
);

CREATE TABLE MASTER_PACKAGE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_SUPPLIER BIGINT(20),
  FK_DOCUMENT BIGINT(20),
  PACKAGE_NAME VARCHAR(255) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  UNIT_TYPE VARCHAR(255) DEFAULT NULL,
  COST DECIMAL(10,2) DEFAULT 0,
  TAX_RATE DECIMAL(10,2) DEFAULT 0,
  MARKUP DECIMAL(10,2) DEFAULT 0,
  QTY DECIMAL(10,2) DEFAULT 0,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_DOCUMENT) REFERENCES EDGE_DOCUMENT (ID),
  CONSTRAINT FOREIGN KEY (FK_SUPPLIER) REFERENCES MASTER_SUPPLIER (ID)
);

CREATE TABLE MAPPER_PACKAGE_ITEM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_MASTER_PACKAGE BIGINT(20),
  FK_MASTER_ITEM BIGINT(20),
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_MASTER_PACKAGE) REFERENCES MASTER_PACKAGE (ID),
  CONSTRAINT FOREIGN KEY (FK_MASTER_ITEM) REFERENCES MASTER_ITEM (ID)
);

CREATE TABLE MASTER_TAX (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TAX_NAME VARCHAR(255) DEFAULT NULL,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE AUDIT_TAX (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_MASTER_TAX BIGINT(20),
  TAX_RATE DECIMAL(10,2),
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  END_DATE DATETIME,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_MASTER_TAX) REFERENCES MASTER_TAX (ID)
);

CREATE TABLE MAPPER_PACKAGE_TAX(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_AUDIT_TAX BIGINT(20),
  FK_MASTER_PACKAGE BIGINT(20),
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_AUDIT_TAX) REFERENCES AUDIT_TAX (ID),
  CONSTRAINT FOREIGN KEY (FK_MASTER_PACKAGE) REFERENCES MASTER_PACKAGE (ID)
);