ALTER TABLE QUOTE_PACKAGES ADD COLUMN QTY DECIMAL(18,2);
ALTER TABLE QUOTE_PACKAGES ADD COLUMN QTY_TYPE VARCHAR(255);
ALTER TABLE QUOTE_PACKAGES ADD COLUMN COST DECIMAL(18,2);

ALTER TABLE QUOTE_ENQUIRY ADD COLUMN HEAR_FROM VARCHAR(255);
ALTER TABLE QUOTE_ENQUIRY ADD COLUMN CLIENT_STORY VARCHAR(2000);
ALTER TABLE QUOTE_ENQUIRY ADD COLUMN IS_CLIENT_STORY_ADDED BIT;