CREATE TABLE MASTER_DRIVER (
  ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
  FULL_NAME  varchar(255) NULL ,
  CODE  varchar(255) NULL ,
  STREET_ONE  varchar(255) NULL ,
  STREET_TWO  varchar(255) NULL ,
  CITY  varchar(255) NULL ,
  STATE  varchar(255) NULL ,
  ZIP_CODE  varchar(255) NULL ,
  COUNTRY  varchar(255) NULL ,
  TELEPHONE_ONE  varchar(255) NULL ,
  MOBILE  varchar(255) NULL ,
  FAX varchar(255) NULL ,
  EMAIL  varchar(255) NULL ,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  FK_DOCUMENT BIGINT(20),PRIMARY KEY (ID),
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FOREIGN KEY (FK_DOCUMENT) REFERENCES EDGE_DOCUMENT (ID)
);

CREATE TABLE QUOTE_ENQUIRY_DRIVER_ALLOCATION (
  ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_ENQUIRY  BIGINT(20) NOT NULL ,
  FK_DRIVER  BIGINT(20) NOT  NULL ,
  ALLOCATED_BY VARCHAR(255) DEFAULT NULL,
  ALLOCATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_ENQUIRY) REFERENCES QUOTE_ENQUIRY (ID),
  CONSTRAINT FOREIGN KEY (FK_DRIVER) REFERENCES MASTER_DRIVER (ID)
)


