CREATE TABLE MASTER_MAIN_MENU_ITEM_CATEGORY (
  ID BIGINT(11) NOT NULL AUTO_INCREMENT,
  MENU_NAME VARCHAR(100) DEFAULT NULL,
  ACTIVE BIT(1) DEFAULT NULL,
  CREATED_BY VARCHAR(100) DEFAULT NULL,
  CREATED_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  FK_EDGE_DOCUMENT_ID BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_EDGE_DOCUMENT_ID) REFERENCES EDGE_DOCUMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MASTER_MENU (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  MENU_NAME VARCHAR(100) DEFAULT NULL,
  MENU_CODE VARCHAR(45) DEFAULT NULL,
  MENU_DESCRIPTION VARCHAR(255) DEFAULT NULL,
  CREATED_BY VARCHAR(200) DEFAULT NULL,
  CREATED_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ACTIVE BIT(1) DEFAULT b'1',
  MENU_COST DECIMAL(10,2) DEFAULT '0.00',
  MENU_PRICE DECIMAL(10,2) DEFAULT '0.00',
  MENU_MARKUP_PRICE DECIMAL(10,2) DEFAULT '0.00',
  FK_EDGE_DOCUMENT_ID BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_EDGE_DOCUMENT_ID) REFERENCES EDGE_DOCUMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MASTER_MENU_ITEM_TYPE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TYPE_NAME VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE MASTER_SUB_MENU_ITEM_CATEGORY (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CATEGORY_NAME VARCHAR(100) DEFAULT NULL,
  ACTIVE BIT(1) DEFAULT NULL,
  CREATED_BY VARCHAR(45) DEFAULT NULL,
  CREATED_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  FK_EDGE_DOCUMENT_ID BIGINT(20) DEFAULT NULL,
  FK_MASTER_MENU_ITEM_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_EDGE_DOCUMENT_ID) REFERENCES EDGE_DOCUMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FOREIGN KEY (FK_MASTER_MENU_ITEM_ID) REFERENCES MASTER_MAIN_MENU_ITEM_CATEGORY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MASTER_MENU_ITEMS (
   ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   ITEM_NAME VARCHAR(100) DEFAULT NULL,
   ITEM_CODE VARCHAR(45) DEFAULT NULL,
   ITEM_DESCRIPTION VARCHAR(255) DEFAULT NULL,
   ITEM_COST DECIMAL(10,2) DEFAULT NULL,
   ITEM_PRICE DECIMAL(10,2) DEFAULT NULL,
   ACTIVE BIT(1) DEFAULT NULL,
   CREATED_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
   CREATED_BY VARCHAR(200) DEFAULT NULL,
   FK_MASTER_SUB_MENU_ITEM_CATEGORY_ID BIGINT(20) NOT NULL,
   FK_EDGE_DOCUMENT_ID BIGINT(20) DEFAULT NULL,
   PRIMARY KEY (ID),
   CONSTRAINT FOREIGN KEY (FK_EDGE_DOCUMENT_ID) REFERENCES EDGE_DOCUMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT FOREIGN KEY (FK_MASTER_SUB_MENU_ITEM_CATEGORY_ID) REFERENCES MASTER_SUB_MENU_ITEM_CATEGORY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MASTER_MENU_DETAILS (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PARENT_ID BIGINT(20) DEFAULT NULL,
  FK_MASTER_MENU_ITEMS_ID BIGINT(20) NOT NULL,
  FK_MASTER_MENU_ITEM_TYPE_ID BIGINT(20) DEFAULT NULL,
  TESTING_REQUIRED BIT(1) DEFAULT b'0',
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_MASTER_MENU_ITEMS_ID) REFERENCES MASTER_MENU_ITEMS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FOREIGN KEY (FK_MASTER_MENU_ITEM_TYPE_ID) REFERENCES MASTER_MENU_ITEM_TYPE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);