CREATE TABLE BOOKING(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	BOOKING_NUMBER VARCHAR(255) DEFAULT NULL,
	FK_QTE_ENQ_WLKTHRGH BIGINT(20),
	IS_ACTIVATED BIT(1) DEFAULT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY (FK_QTE_ENQ_WLKTHRGH) REFERENCES QUOTE_ENQUIRY_WALKTHROUGH (ID),
	PRIMARY KEY (ID)
);

INSERT INTO EDGE_MENU_ITEM (IS_ACTIVATED, MENU_NAME, PRIORITY, URL, ICON)
VALUES (b'1', 'Transport', '1', '/driver', 'directions_car');

INSERT INTO EDGE_MENU_ITEM (IS_ACTIVATED, MENU_NAME, PRIORITY, URL, ICON)
VALUES (b'1', 'Voucher', '1', NULL, 'local_movies');

INSERT INTO EDGE_SUBMENU_ITEM (IS_ACTIVATED, MENU_NAME, FK_EDGE_MENU_ITEM, PRIORITY, URL)
VALUES (b'1', 'Transport Voucher', (SELECT ID FROM EDGE_MENU_ITEM WHERE MENU_NAME = 'Voucher' LIMIT 1), '1', '/transportVoucher');

CREATE TABLE MAPPER_PACKAGE_DOCUMENT(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_DOCUMENT BIGINT(20),
  FK_PACKAGE BIGINT(20),
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_DOCUMENT) REFERENCES EDGE_DOCUMENT (ID),
  CONSTRAINT FOREIGN KEY (FK_PACKAGE) REFERENCES MASTER_PACKAGE (ID)
);

ALTER TABLE QUOTE_ENQUIRY_DRIVER_ALLOCATION ADD COLUMN ACTIVE BIT;
ALTER TABLE QUOTE_ENQUIRY_DRIVER_ALLOCATION ADD COLUMN UNALLOCATED_BY VARCHAR(255);
ALTER TABLE QUOTE_ENQUIRY_DRIVER_ALLOCATION ADD COLUMN UNALLOCATED_DATE DATETIME;

CREATE TABLE SYSTEM_ID_GENERATOR (
	ID BIGINT NOT NULL AUTO_INCREMENT ,
	TYPE VARCHAR(255) NULL ,
	NUMBER INT NULL ,
	PRIMARY KEY (ID)
);

CREATE TABLE VOUCHER (
	ID BIGINT NOT NULL AUTO_INCREMENT ,
	FK_SYS_ID_GENERATOR BIGINT NOT NULL ,
	VOUCHER_TYPE VARCHAR(255) NULL ,
	VOUCHER_NUMBER VARCHAR(255) NULL ,
	FK_BOOKING BIGINT,
	ACTIVE BIT,
	PRIMARY KEY (ID),
	CONSTRAINT FOREIGN KEY (FK_SYS_ID_GENERATOR) REFERENCES SYSTEM_ID_GENERATOR (ID),
	CONSTRAINT FOREIGN KEY (FK_BOOKING) REFERENCES BOOKING (ID)
);

INSERT INTO SYSTEM_ID_GENERATOR(TYPE, NUMBER) VALUES ('VOUCHER', '0');
ALTER TABLE QUOTE_ENQUIRY_DRIVER_ALLOCATION ADD COLUMN FK_VOUCHER BIGINT;
ALTER TABLE QUOTE_ENQUIRY_DRIVER_ALLOCATION ADD CONSTRAINT FK_VOUCHER FOREIGN KEY (FK_VOUCHER) REFERENCES VOUCHER (ID) ON DELETE CASCADE;
