ALTER TABLE QUOTE_ENQUIRY ADD COLUMN FK_QTE_ENQ_WALKTHROUGH BIGINT;
ALTER TABLE QUOTE_ENQUIRY ADD CONSTRAINT FK_QTE_ENQ_WALKTHROUGH FOREIGN KEY (FK_QTE_ENQ_WALKTHROUGH) REFERENCES QUOTE_ENQUIRY_WALKTHROUGH (ID) ON DELETE CASCADE;

ALTER TABLE MASTER_MENU_DETAILS ADD COLUMN FK_MASTER_MENU_ID BIGINT;
ALTER TABLE MASTER_MENU_DETAILS ADD CONSTRAINT FK_MASTER_MENU_ID FOREIGN KEY (FK_MASTER_MENU_ID) REFERENCES MASTER_MENU (ID) ON DELETE CASCADE;