ALTER TABLE QUOTE_ENQUIRY_WALKTHROUGH_SETUP ADD COLUMN FK_DRIVER_ALLOCATION BIGINT;
ALTER TABLE QUOTE_ENQUIRY_WALKTHROUGH_SETUP ADD CONSTRAINT FK_DRIVER_ALLOCATION FOREIGN KEY (FK_DRIVER_ALLOCATION) REFERENCES QUOTE_ENQUIRY_DRIVER_ALLOCATION (ID) ON DELETE CASCADE;

ALTER TABLE QUOTE_ENQUIRY ADD COLUMN ENQ_STATUS INT DEFAULT 1;
