INSERT INTO EDGE_MENU_ITEM (IS_ACTIVATED, MENU_NAME, PRIORITY, URL, ICON) VALUES (b'1', 'Booking', '2', '/booking', 'recent_actors');

ALTER TABLE SYSTEM_ID_GENERATOR ADD COLUMN CHARACTOR VARCHAR(10);

ALTER TABLE BOOKING ADD COLUMN DEPOSIT_AMOUNT DECIMAL(18,2);

CREATE TABLE ACT_LOG_QUOTE_ENQUIRY(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	LOG_TYPE VARCHAR(255) DEFAULT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FK_QUOTE_ENQUIRY BIGINT,
	CONSTRAINT FOREIGN KEY (FK_QUOTE_ENQUIRY) REFERENCES QUOTE_ENQUIRY (ID),
	PRIMARY KEY (ID)
);