CREATE TABLE USER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  FIRSTNAME VARCHAR(255) DEFAULT NULL,
  LAST_PASSWORD_RESET_DATE DATE DEFAULT NULL,
  LASTNAME VARCHAR(255) DEFAULT NULL,
  PASSWORD VARCHAR(255) DEFAULT NULL,
  USERNAME VARCHAR(255) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE DATE DEFAULT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO USER(`IS_ACTIVATED`, `EMAIL`, `FIRSTNAME`, `LASTNAME`, `PASSWORD`, `USERNAME`, `CREATED_BY`, `CREATED_DATE`) VALUES (1, 'stelan.slt@gmail.com', 'Stelan Briyan' , 'Simonsz', '$2a$10$.a6jBwOWes9krB0SAFKgwOVeewPMTKQlOobM29gIi6lPraZwFhbaW', 'SYSTEM','SYSTEM', CURRENT_TIMESTAMP);

CREATE TABLE ROLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ROLE VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE EDGE_MENU_ITEM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  MENU_NAME VARCHAR(255) DEFAULT NULL,
  PRIORITY DOUBLE DEFAULT NULL,
  URL VARCHAR(255) DEFAULT NULL,
  ICON VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE EDGE_SUBMENU_ITEM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  MENU_NAME VARCHAR(255) DEFAULT NULL,
  FK_EDGE_MENU_ITEM BIGINT(20) DEFAULT NULL,
  PRIORITY DOUBLE DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_EDGE_MENU_ITEM) REFERENCES EDGE_MENU_ITEM (ID)
);

CREATE TABLE MAPPER_USER_ROLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FK_ROLE bigint(20) DEFAULT NULL,
  FK_USER bigint(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_USER) REFERENCES USER (ID),
  CONSTRAINT FOREIGN KEY (FK_ROLE) REFERENCES ROLE (ID)
);

CREATE TABLE MAPPER_USER_MENU (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  FK_MENU_ITEM BIGINT(20) DEFAULT NULL,
  FK_SUB_MENU_ITEM BIGINT(20) DEFAULT NULL,
  FK_ROLE BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT FOREIGN KEY (FK_ROLE) REFERENCES ROLE (ID),
  CONSTRAINT FOREIGN KEY (FK_SUB_MENU_ITEM) REFERENCES EDGE_SUBMENU_ITEM (ID),
  CONSTRAINT FOREIGN KEY (FK_MENU_ITEM) REFERENCES EDGE_MENU_ITEM (ID)
);