INSERT INTO EDGE_MENU_ITEM(IS_ACTIVATED, MENU_NAME, PRIORITY, URL, ICON) VALUES (1, 'Masters', '1', '/master', 'content_paste');

CREATE TABLE MASTER_EVENT_TYPE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  EVENT_TYPE VARCHAR(255) DEFAULT NULL,
  CODE VARCHAR(10) DEFAULT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE MASTER_VENUE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  VENUE_NAME VARCHAR(255) DEFAULT NULL,
  STREET_ONE VARCHAR(255) DEFAULT NULL,
  STREET_TWO VARCHAR(255) DEFAULT NULL,
  COUNTRY VARCHAR(255) DEFAULT NULL,
  CITY VARCHAR(255) DEFAULT NULL,
  STATE VARCHAR(255) DEFAULT NULL,
  WEB VARCHAR(255) DEFAULT NULL,
  PHONE VARCHAR(255) DEFAULT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);