UPDATE USER SET IS_ADMIN = 1 WHERE USERNAME = 'SYSTEM';
INSERT INTO EDGE_MENU_ITEM (IS_ACTIVATED, MENU_NAME, PRIORITY, URL, ICON) VALUES (b'1', 'Enquiries', '1', '/enquiry', 'view_comfy');

CREATE TABLE MASTER_CUSTOMER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255) DEFAULT NULL,
  LASTNAME VARCHAR(255) DEFAULT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  MOBILE VARCHAR(20) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE QUOTE_ENQUIRY (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  START_DATE DATETIME,
  END_DATE DATETIME,
  PAX INT DEFAULT 0,
  DESCRIPTION VARCHAR(500) DEFAULT NULL,
  FK_EVENT_TYPE BIGINT(20),
  FK_VENUE_SPACE BIGINT(20),
  FK_CUSTOMER BIGINT(20),
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  IS_PROCESSED BIT(1) DEFAULT 0,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_EVENT_TYPE) REFERENCES MASTER_EVENT_TYPE (ID),
  CONSTRAINT FOREIGN KEY (FK_VENUE_SPACE) REFERENCES MASTER_VENUE_SPACE (ID),
  CONSTRAINT FOREIGN KEY (FK_CUSTOMER) REFERENCES MASTER_CUSTOMER (ID)
);