ALTER TABLE QUOTE_ENQUIRY MODIFY  DESCRIPTION VARCHAR(2000);
ALTER TABLE MASTER_VENUE_SPACE MODIFY  DESCRIPTION VARCHAR(2000);

CREATE TABLE EDGE_DOCUMENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FILE_NAME VARCHAR(255) DEFAULT NULL,
  FILE_PATH VARCHAR(255) DEFAULT NULL,
  EXT VARCHAR(100) DEFAULT NULL,
  FILE_SIZE_BYTES BIGINT(20) DEFAULT 0,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT(1) DEFAULT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE MASTER_VENUE_SPACE ADD COLUMN FK_DOCUMENT BIGINT(20);
ALTER TABLE MASTER_VENUE_SPACE ADD CONSTRAINT FK_DOCUMENT FOREIGN KEY (FK_DOCUMENT) REFERENCES EDGE_DOCUMENT (ID) ON DELETE CASCADE;

CREATE TABLE MAPPER_VENUE_SPACE_DOCUMENT(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_DOCUMENT BIGINT(20),
  FK_VENUE_SPACE BIGINT(20),
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_DOCUMENT) REFERENCES EDGE_DOCUMENT (ID),
  CONSTRAINT FOREIGN KEY (FK_VENUE_SPACE) REFERENCES MASTER_VENUE_SPACE (ID)
);

ALTER TABLE MASTER_EVENT_TYPE ADD COLUMN FK_DOCUMENT BIGINT(20);
ALTER TABLE QUOTE_ENQUIRY ADD COLUMN IS_ALLOCATED BIGINT(20) DEFAULT 0;