UPDATE USER SET IS_REGISTERED = 1 WHERE (USERNAME = 'SYSTEM');
INSERT INTO EDGE_MENU_ITEM (IS_ACTIVATED, MENU_NAME, PRIORITY, URL, ICON) VALUES (b'1', 'Enquiries', '1', '/enquiry', 'view_comfy');

CREATE TABLE QUOTE_ENQUIRY_ALLOCATION (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_USER BIGINT(20),
  FK_QUOTE_ENQUIRY BIGINT(20),
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

ALTER TABLE QUOTE_ENQUIRY ADD COLUMN FK_QE_ALLOCATION BIGINT(20);
ALTER TABLE QUOTE_ENQUIRY ADD CONSTRAINT FK_QE_ALLOCATION FOREIGN KEY (FK_QE_ALLOCATION) REFERENCES QUOTE_ENQUIRY_ALLOCATION (ID) ON DELETE CASCADE;

CREATE TABLE MAPPER_GROUP_ROLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_ROLE BIGINT(20),
  GROUP_CODE VARCHAR(20),
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_ROLE) REFERENCES ROLE (ID)
);

INSERT INTO ROLE (ROLE) VALUES ('Sales Manager');
INSERT INTO MAPPER_GROUP_ROLE (FK_ROLE, GROUP_CODE) VALUES ((SELECT R.ID FROM ROLE R WHERE R.ROLE = 'Sales Manager' LIMIT 1), 'G001');

ALTER TABLE MASTER_CUSTOMER ADD COLUMN PROVIDER VARCHAR(200);
ALTER TABLE MASTER_CUSTOMER ADD COLUMN PROFILE_PIC VARCHAR(200);
ALTER TABLE MASTER_VENUE_SPACE ADD COLUMN MIN_PAX INT;
ALTER TABLE MASTER_VENUE ADD COLUMN DESCRIPTION VARCHAR(3000);