CREATE TABLE MASTER_VENUE_SPACE_FACILITY (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_VENUE_SPACE BIGINT(20),
  FACILITY VARCHAR(255),
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT DEFAULT 1,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_VENUE_SPACE) REFERENCES MASTER_VENUE_SPACE(ID)
);

CREATE TABLE EDGE_CALENDAR (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(255),
  START_DATE DATETIME,
  END_DATE DATETIME,
  ALL_DAY BIT DEFAULT 0,
  CLASS_NAME VARCHAR(100) DEFAULT 'event-azure',
  URL VARCHAR(255) DEFAULT NULL,
  USERNAME VARCHAR(255) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT DEFAULT 1,
  PRIMARY KEY (ID)
);