CREATE TABLE EDGE_GOOGLE_LOCATION (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  LAT DECIMAL(10,8) DEFAULT 0,    
  LNG DECIMAL(10,7) DEFAULT 0,    
  ADDRESS VARCHAR(255) DEFAULT NULL,
  PLACE_ID VARCHAR(255) DEFAULT NULL,
  URL VARCHAR(255) DEFAULT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT DEFAULT 1,
  PRIMARY KEY (ID)
);

CREATE TABLE QUOTE_ENQUIRY_WALKTHROUGH_SETUP (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_GOOGLE_LOCATION BIGINT(20),
  FK_CALENDAR BIGINT(20),
  FK_QUOTE_ENQUIRY BIGINT(20),
  MESSAGE VARCHAR(255) DEFAULT NULL,
  PICKUP_TIME TIME,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVATED BIT DEFAULT 1,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (FK_GOOGLE_LOCATION) REFERENCES EDGE_GOOGLE_LOCATION (ID),
  CONSTRAINT FOREIGN KEY (FK_CALENDAR) REFERENCES EDGE_CALENDAR (ID),
  CONSTRAINT FOREIGN KEY (FK_QUOTE_ENQUIRY) REFERENCES QUOTE_ENQUIRY (ID)
);

ALTER TABLE EDGE_CALENDAR ADD COLUMN CATEGORY VARCHAR(255);
ALTER TABLE QUOTE_ENQUIRY ADD COLUMN STATUS INT DEFAULT 0;
ALTER TABLE EDGE_DOCUMENT ADD COLUMN ALT_PATH VARCHAR(255);